### ISSUE TITLE
Get listed on the meta-awesome list

### ISSUE THREAD

**Issue by zimbatm** [nix-community/awesome-nix#1]
https://github.com/sindresorhus/awesome

There are some requirements: https://github.com/sindresorhus/awesome/blob/master/contributing.md

**Comment by houstdav000** [comment]
Considering the requirement for passing the [awesome-lint](https://github.com/sindresorhus/awesome-lint), and that we may want to ensure other constraints on the lists, could we build this as a flake and have it be checked by Hydra with nix flake check?

Note: would probably be best to get awesome-lint added to nixpkgs first.

**Comment by zimbatm** [comment]
I would accept a GitHub Actions PR. It's probably the easiest.

**Comment by houstdav000** [comment]
Additionally, per [the requirements](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list), the default branch has to be `main`:

> The default branch should be named main, not master.

@zimbatm would you be able to make this change?

**Comment by zimbatm** [comment]
It's unfortunate. I don't think that pushing ideology and politics is appropriate for a technological project.

**Comment by houstdav000** [comment]
I can see the benefit of ensuring that all repositories share the same default branch name for consistency's sake, but don't really have an opinion otherwise. :shrug:

**Comment by houstdav000** [comment]
I didn't realize it at the time, since I'm so used to 'main' at this point, but the GitHub action I copied uses 'main' as the target branch, so that's why it didn't run.

**Comment by houstdav000** [comment]
Okay, one last issue caught by `awesome-lint` that needs a decision made: `awesome-nix-hpc` is listed twice in the `README.md`, once on line 72 under the "High Performance Computing" header, and on line 143 under the "Overlays" header.

Which one do we keep?

Considering it itself is not actually an overlay but an Awesome list for high performance utilities, I might recommend not only getting rid of the "Overlays" one, but removing both and contacting the maintainer of `awesome-nix-hpc` to integrate their list into ours instead

**Comment by Mic92** [comment]
Drop the hpc section for now.

**Comment by zimbatm** [comment]
@houstdav000 would you be interested in taking over the maintainership of this project? I am happy with the changes that you are proposing. I also think that as a maintainer you are free to rename the master branch if that is what you want to do.

**Comment by houstdav000** [comment]
Sure. I'd be glad to do it. Of course, I'll be asking for a  lot of input still if I do, since I'm still learning a lot about Nix and what would best go on the list.

**Comment by houstdav000** [comment]
Alright, thanks for doing that. I will still have to ask if a repository admin can [rename the default branch](https://github.com/github/renaming#renaming-existing-branches), since that has to be done in the GitHub repository settings by an admin.

**Comment by zimbatm** [comment]
You are now an admin on the repo as well :)

**Comment by houstdav000** [comment]
I think it's coming along pretty nicely.

When we go to make the pull request into the [Awesome list](https://github.com/sindresorhus/awesome), what section would be best to add it to? Considering this list encompasses the Nix expression language, NixOS, and the Nixpkgs ecosystem, I'd personally put it as a "Platform".

Thoughts?

**Comment by Mic92** [comment]
Platform sounds like the best fit.

**Comment by houstdav000** [comment]
Looks like we've got it: https://twitter.com/awesome__re/status/1378072664896532480

https://github.com/sindresorhus/awesome

Thanks for the help @Mic92 and @zimbatm !

**Comment by zimbatm** [comment]
Nice work @houstdav000
