### ISSUE TITLE
Add nixvim

### ISSUE THREAD

**Issue by legendofmiracles** [nix-community/awesome-nix#109]
https://github.com/pta2002/nixvim

I'm unsure in what section to put this, but I feel like this belongs here

cc: @pta2002

**Comment by pta2002** [comment]
I'd say it's a NixOS module, but looking at the rest of the things on here, in spirit it's closer to the things on the overlays section? I don't know, I'd put it alongside home-manager since that's the closest thing to this.

**Comment by houstdav000** [comment]
Hmm, makes me wonder if home-manager is in the right section itself. I'd definitely say NixVim looks like it would go in the NixOS Modules section, and that home-manager might need to be moved there as well.
