### ISSUE TITLE
centralize collection of resources and recommendations

### ISSUE THREAD

**Issue by fricklerhandwerk** [nix-community/awesome-nix#124]
there are multiple locations which overlap in serving the overview function for different topics:
- https://nixos.org/learn.html
- https://nixos.org/community/
- https://nix.dev/recommended-reading
- https://nixos.wiki/wiki/Resources

proposal to increase centralization and ease curation:
- determine a location for collections of resources on each topic
- remove redundant information from the other locations
- link appropriately

examples:
1. learning Nix
  - "learning Nix" is actually learning/understanding multiple things
    - how to navigate the ecosystem
    - `nix` commands
    - Nix language syntax and semantics
    - `builtins` and `pkgs.lib`
    - `nixpkgs` patterns and idioms
    - language-specific patterns and tooling
    - NixOS modules
    - software development with Nix
    - contributing to the ecosystem
    - ...
  - as [we decided](https://github.com/NixOS/nix.dev/issues/285#issuecomment-1198131047) to make nix.dev the official Nix learning resource, curating additional learning resources should be managed there
  - suggestion: only link to nix.dev from here
2. communication channels
  - community communication channels are presented on nixos.org
  - as [we decided](https://discourse.nixos.org/t/2022-06-23-documentation-team-meeting-notes-2/20005) and formalized for [Summer of Nix 2022](https://discourse.nixos.org/t/summer-of-nix-documentation-stream/20351#how-to-contribute-to-documentation-6) and [Nix documentation team](https://discourse.nixos.org/t/documentation-team-flattening-the-learning-curve/20003#responsibilities-4) the NixOS Wiki should be the staging area for edge cases and auxiliary information
  - [NixOS Wiki: Get In Touch](https://nixos.wiki/wiki/Get_In_Touch) links to nixos.org and additionally lists unofficial channels
  - suggestion: only link to nixos.org from here
  
related: https://github.com/NixOS/nixpkgs/issues/121403 (Bring the Haskell documentation back into nixpkgs)

**Comment by houstdav000** [comment]
I haven't kept up super well with Discourse (lot of stuff with work recently), so I can certainly agree with some of those consolidations.

As I mentioned in #123, an awesome list is to provide _projects_ that are truly "awesome". As such, providing an exhaustive list of resources is specifically beyond its purview. If coordinated to move these non-project items to the Wiki (where they probably should only have been in the first place) or even to the nixos org site, it might make more sense to remove _all_ of these items entirely, leaving only a link to a more exhaustive resource like <https://nixos.org/>.

**Comment by cyntheticfox** [comment]
Closing, as this is beyond the scope of the project, and seems to be documented elsewhere now.
