### ISSUE TITLE
Selection doesn't work.

### ISSUE THREAD

**Issue by DaKingof** [nix-community/awesome-nix#186]
When attempting to select the method used with tab it only comes up with option 0 on zsh. When I try typing in another option it just says hit tab to see options. The only thing I can do is hit enter. Typing any number 0-5 does nothing but tell me to hit tab.

**Comment by cyntheticfox** [comment]
What tool/CLI are you using? I'm not sure either what component you're referring to or what you're trying to do?

**Comment by DaKingof** [comment]
> What tool/CLI are you using? I'm not sure either what component you're referring to or what you're trying to do?

omg. Not sure why I posted this in here. It was supposed to be for ```nix-init```. Will close and repost there.
