### ISSUE TITLE
HPC specific things

### ISSUE THREAD

**Issue by freuk** [nix-community/awesome-nix#24]
There's a list of links to High Performance Computing - related things here: https://github.com/freuk/awesome-nix-hpc .
Should I include a link or rather copy over some of that the content in a PR?

**Comment by zimbatm** [comment]
Might as well merge those lists together and create a consistent view. Shall I invite you to become a maintainer on this project?

**Comment by zimbatm** [comment]
I went ahead and invited you. Make yourself at home! :)
