### ISSUE TITLE
nixkite - Nix module for buildkite pipelines

### ISSUE THREAD

**Issue by johnae** [nix-community/awesome-nix#31]
I realize this could be viewed as shameless self promotion but anyway, I've created nixkite - https://github.com/johnae/nixkite which is a Nix module for generating buildkite pipelines... a bit opinionated in that it only supports DAG pipelines (eg. the relatively new functionality on buildkite).

I'm using it myself in https://github.com/johnae/nixos-configuration (and other private repos as well).
Maybe it is worthy of including on this list? It likely doesn't have any users at the moment other than me.

**Comment by zimbatm** [comment]
Nice!

I don't know if it should be part of awesome-nix just yet but it does deserve some promotion.

You might want to announce it on discourse: https://discourse.nixos.org/c/announcements/8

**Comment by johnae** [comment]
Alright. Thanks, I'll do that and see if someone else might be interested.

**Comment by johnae** [comment]
Just did what you suggested here: https://discourse.nixos.org/t/announcing-nixkite-buildkite-pipelines-using-the-nixos-module-system/7266
