### ISSUE TITLE
https://github.com/nix-community/pypi2nix vs pip2nix?

### ISSUE THREAD

**Issue by zokrezyl** [nix-community/awesome-nix#9]

**Comment by zimbatm** [comment]
sorry I don't know. maybe ask in the pypi2nix project instead?

**Comment by zokrezyl** [comment]
Sorry was not enough verbose: pypi2nix seems to be alive while pip2nix not maintained for a while... Was just a hint to update the list

**Comment by zimbatm** [comment]
good point
