### ISSUE TITLE
Question: Where to put wrappers?

### ISSUE THREAD

**Issue by lucasew** [nix-community/awesome-nix#99]
I did a thing  [1] using the nixpkgs module system to generate custom configurations for VSCode, I am looking to do more of these things like Firefox, Chrome and Neovim.

Should be added a new section for content like this?

[1] https://github.com/lucasew/nix-vscode

**Comment by houstdav000** [comment]
For wrappers, a new section would be good. 

For that particular repository, I just have the same question I raised in #94 and #96, whether the project is too young to put on the list. It looks valuable, just very new. Opening a PR for it and talking about it on the Discourse are typically good ways to get people to look at it though

**Comment by tannerlegvold** [comment]
Two more wrappers are [nixvim](https://github.com/pta2002/nixvim) and [jupyterWith](https://github.com/tweag/jupyterWith). jupyterWith in particular should really be mentioned.

**Comment by cyntheticfox** [comment]
If this project still works and is useful, free to reopen. Separately, @tannerlegvold, if you'd like to, please open a PR to add `jupyenv`, since that's replaced `jupyterWith`
